<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "root");
if (!defined("PJ_PASS")) define("PJ_PASS", "");
if (!defined("PJ_DB")) define("PJ_DB", "ahmet_driver");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/Ahmet/driverapp/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "D:/PHP/PHP8.212/htdocs/Ahmet/driverapp/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://localhost/Ahmet/driverapp/");
if (!defined("PJ_SALT")) define("PJ_SALT", "SJ5B62UI");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "NjEyODc0OTU4NjUwMzQ3NjcyNzE3ODM5ODE3OTU4NjE3NjY1MDEyNjEwOTMzMzIzMjU1Njk4NjQ1MzYyODE3NDEwNDgwNzk4OTUxNDI4MTM0ODE3MzI3MDM5MDEyMDA4OCAzNDM0NDcwNjA3MzgyNzc0ODAwMDgwOTQxNjUyODM1MTU3Mzc0MTk3Mjc4Njc4MTE5MDk2NDY3MDc1MDM1NTQxNDUyMTgzNDU2Nzk0NDExOTc2NDQwNDQ4OTIzOTA1MTgyMTkgMzgzNDg5NjQ1MTA2MjEzNTg0MjMwMTY5NjUxOTIyNzQ2MzEyMTcwMDg4MDkwMzg2OTMyMTk2Mjc0MDcwNDA4ODgwMTkxMDc2OTA1ODY5MjEyMjQ5Mjg3MzI5MzE0NDI2NTkzIDMxNTMyODQyNTE0MTMzNTIxNDA0MTQ1NzI5MzM0Mzc4NjgyNTUwMzA3MzMyOTI1NjU3MzcwMjc1NDQ1MjUxMTM4OTE4MDIyNDQzNjk5MjYwMzgzNDQ4ODAxNDQ0ODQ3NTg0MSAxMTczNTA4OTEwNDYzMTYwNTk4ODM2MDQ1NTQzNjgwMTAwODM3OTg5NDg5MzA5OTU2MTkxNTI1Mjk3NjkyNzA2NjI5NjczMzkwMTI4NDI4MDU2NTE1MzM4Mzk5ODIwMTg1NjY2IDUwMTQ4MDcyMDkwMzMxNjUxMDA2MDI0NTQ2MzU3MjkwNzE2NTcxNjA0OTEyNDc5Mjg3NDA2MDQ3MjYwNjk4MDk1NzYzMTYyNjA4MjMxODMxMDkwNDE3NTIxMTYxODI2NTI2OCA3NzA1MzUwNjU2OTA4ODEwNzI0NjE0NDMwMDA4MTMyNDA2MDM3MDgzNjcxOTM1NzA1ODEwMTE1MTcyMTM5NTA1NjEzMDU3NTU5NzkyNjA0ODQxMDYzMjQ0MjU5NzIyNTYzODU=");
?>